### ISSUE TITLE
How to stop selected Month + Day objects from changing color to black

### ISSUE THREAD

**Issue by MariuszGSL** [flavienlaurent/datetimepicker#10]
The large Month + Day textView objects displayed in the top part of the picker dialog are initially shown in blue colour.
After clicking the Done button and immediately re-selecting the date picker dialog, those two objects change their colour to black.
I would like to always have them displayed in blue.
How can I change this feature permanently in your library ?

**Comment by flavienlaurent** [comment]
d0eb5c4d23023e199ea43963cd21ae6553a682f6

**Comment by MariuszGSL** [comment]
Thank you. The fix works very well.
