### ISSUE TITLE
Orientation Changes

### ISSUE THREAD

**Issue by eric-hc** [flavienlaurent/datetimepicker#11]
The date picker does not currently adjust itself on rotation to landscape. In Google Calendar, the top and bottom of the picker separate, and are placed side-by-side. It'd be great if this could be fixed, because the "Done" button isn't visible currently in landscape.

**Comment by MariuszGSL** [comment]
On my phone, Samsung Galaxy Note 2, the date picker adjusts itself perfectly in landscape mode, with the two sections placed correctly side by side. The Done button is visible, no problems.
However, I have not tested it on any other devices or different screen sizes.
You need to be specific about the device you are using, when reporting these types of issues.

**Comment by flavienlaurent** [comment]
MariuszGSL is right. There is a specific layout in landscape mode. Works like a charm on my gnex so your issue must be specific on your device.

**Comment by eric-hc** [comment]
Right, sorry about that. I'm on a Nexus 4, not using any custom DPI settings or anything and the Google Calendar picker rotates correctly.

**Comment by gabrielittner** [comment]
On my Nexus 4 it works fine.

**Comment by flavienlaurent** [comment]
@ericcarboni can you please post a screenshot ?

**Comment by eric-hc** [comment]
Yeah sure, here it is on my N4 within my app. I'm on stock 4.3 now, but it was still like this on CyanogenMod 4.2.2
![screenshot_2013-07-24-21-16-59](https://f.cloud.github.com/assets/1885157/853018/318e65de-f4c8-11e2-9cd6-eb56d2f2bf86.png)

**Comment by flavienlaurent** [comment]
Do you still have an issue on this?

**Comment by DineshAnandan** [comment]
Hi here is one serious issue in your sample app.

It is easily reproducible from ur sample app.
1.Click the button. The date picker dialog appears.
2. Change the orientation.
3.Tap any date and "done".

When all the above three steps over, you cannot see the date as be set.

please guide me to handle this issue soon..

**Comment by marcusforsberg** [comment]
Hello!

I also have a problem with landscape mode on my Sony Xperia Z running Android 4.2.2.
It displays just fine in portrait, and if I open the dialog in landscape mode. However, if I open it in portrait mode and then switch to landscape, this is what it looks like:

![screenshot_2013-11-30-17-16-39](https://f.cloud.github.com/assets/1009069/1648954/e5972b5a-59d2-11e3-8158-4d1155bd8a8c.png)

And the other way around if I open it in landscape, then switch to portrait:

![screenshot_2013-11-30-17-20-54](https://f.cloud.github.com/assets/1009069/1648955/19b2db78-59d3-11e3-932d-67a4d00416f7.png)

**Comment by MariuszGSL** [comment]
I also use Sony Xperia Z tablet with Android 4.2.2 and cannot replicate the problems with switching the DateTimePicker from landscape to portrait and vice versa. Works perfectly in my application and in other applications that use this component.  

Keep in mind that I have not updated to the latest DateTimePicker code since 7 July 2013, when some critical code changes have been made.

**Comment by flavienlaurent** [comment]
@DineshAnandan please take a look on the example. There is a good way to do it.
@marcusforsberg I'm sorry but I can't reproduce your problem... what's the app?
@MariuszGSL can you try with the latest version?

**Comment by flavienlaurent** [comment]
@marcusforsberg it looks like you have the landscape layout in portrait mode and the portrait layout in landscape mode ...

@MariuszGSL can you please try with the latest version?

**Comment by MariuszGSL** [comment]
@flavienlaurent  I have tried to replace my old datepicker library (from July 2013) in Eclipse with the new one without success. I am getting compilation errors and cannot get it working. 
I had to reverse back to the earlier library from July after several hours of struggle. 
I needed to do the following changes in the original (July) datepicker library code before compiling:
#1. in DatePickerDialog.java   replaced import android.support.v4.app.DialogFragment with
    import android.app.DialogFragment
#2. in layout date_picker_selected_date.xml  changed the order of day and month (swapped them around to have the date appear above the month).
Also made the same (#1) change in the new module TimePickerDialog.java

Please suggest the best, simplest, full proof method to replace the library code with the new one, in order to test it for you.

**Comment by raymondlam** [comment]
@MariuszGSL Did you include the android-support v4 library to the datetimepicker library? (Also the nineoldandroids library as well)? That is likely why you didn't have a reference to the support Dialog Fragment. The libraries used to be included in the github but now they have been removed. If you aren't using gradle, you'll need to add them back manually.

**Comment by MariuszGSL** [comment]
@raymondlam  Yes, I have copied both libraries from the old Datetimepicker project and tried to compile it without success.
I don't actually need the support v4 library, as I do not want to use it in my main project. I need to have the 
import android.support.v4.app.DialogFragment removed from the DatePickerDialog.java code and replaced with android.app.DialogFragment.
I will explore the gradle and see if this will make a difference.
The July version of datetimepicker works perfectly well in my main project on all devices I have tested it and I have no need for the timepicker module.  I also don't want to waste several more hours trying to fight the compilation of the updated library code.

**Comment by flavienlaurent** [comment]
@MariuszGSL 
- support v4 library is needed because we want to backport the picker on 2.1+
- date_picker_selected_date.xml is the same as https://android.googlesource.com/platform/frameworks/opt/datetimepicker/+/master/res/layout/date_picker_selected_date.xml

What are the compilation issues?

**Comment by sumedhulhe** [comment]
Simple solution for date picker is here[https://stackoverflow.com/a/52422586/7513281](url) smart fix for this small issue.
