### ISSUE TITLE
unable to resolve the ddependency

### ISSUE THREAD

**Issue by abhi9wagadre** [flavienlaurent/datetimepicker#116]
Error:(27, 13) Failed to resolve: com.github.flavienlaurent.datetimepicker:library:VERSION
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by abhi9wagadre** [comment]
Sorry the issue. I dint mention the version number in the compile gradle file. Hence closing the issue.

**Comment by iamyuzhe** [comment]
How can I solve the problem?
