### ISSUE TITLE
TimePicker Status

### ISSUE THREAD

**Issue by chrisonline** [flavienlaurent/datetimepicker#12]
The readme wrotes "timepicker is in progress"!
Is there any news about the time picker status?

**Comment by flavienlaurent** [comment]
Unfortunatly, no time to work on ... I hope starting in a couple of days.

**Comment by chrisonline** [comment]
Perfekt, thanks for the update.

**Comment by gabrielittner** [comment]
The official datetimepicker is now opensource. Probably will save you some work: https://plus.google.com/u/0/106956142297978494072/posts/gUNMeZ1eFZW
