### ISSUE TITLE
Porting to Gradle

### ISSUE THREAD

**Issue by tkhduracell** [flavienlaurent/datetimepicker#13]
Any thoughts on porting to Gradle and the AAR-format?

http://tools.android.com/tech-docs/new-build-system/aar-format

**Comment by flavienlaurent** [comment]
Good idea. I'm going to focus on this asap

**Comment by flavienlaurent** [comment]
Try this https://github.com/flavienlaurent/datetimepicker/raw/master/datetimepicker-library.aar
