### ISSUE TITLE
Time Picker support

### ISSUE THREAD

**Issue by jjpe** [flavienlaurent/datetimepicker#14]
It seems there is no time picker accompanying the date picker.
Is there anything happening on that front?

**Comment by flavienlaurent** [comment]
Do you know TimePicker is open source?

**Comment by jjpe** [comment]
Yes, I was merely hoping some work on that was already underway, yet unmerged (something that is invisible from github).
TBH I merely wanted to send a private message but I've found no way to do that on github yet.

**Comment by flavienlaurent** [comment]
I didn't start anything on TimePicker. It may be interesting to backport to 2.1+ and to make it more customizable

**Comment by jjpe** [comment]
I have other motivations: I'd like to use it in my own project.
I'll take a look at how much work/code the DatePicker was to create estimate from that the work the TimePicker will take. And _if_ I think I can do it quickly enough (so as to not distract too much from my own project), then I'll pick it up and let you know in a future post on this "bug".

**Comment by edisonw** [comment]
I have added TimePicker on my fork: https://github.com/edisonw/datetimepicker, feel free to fork it.

**Comment by jjpe** [comment]
Cool stuff, thanks!
