### ISSUE TITLE
Does it work? 

### ISSUE THREAD

**Issue by huteri** [flavienlaurent/datetimepicker#15]

**Comment by flavienlaurent** [comment]
Be more explicit

**Comment by huteri** [comment]
Sorry, I had bad internet connection before I did not realize my issue has been posted, but your library needs api level 11 for style="?android:attr/buttonBarStyle" and   style="?android:attr/buttonBarButtonStyle"

**Comment by DrGasmo** [comment]
You can solve that by following along with this post: http://stackoverflow.com/questions/14297309/android-button-bar-in-holo
