### ISSUE TITLE
Set Min and Max date

### ISSUE THREAD

**Issue by sureshkumarece** [flavienlaurent/datetimepicker#16]
Nice work.How to set MinDate and MaxDate?

**Comment by sureshkumarece** [comment]
modified myself. thanks

**Comment by MiguelCatalan** [comment]
How about a pull request?

**Comment by flavienlaurent** [comment]
yes go-ahead

**Comment by Marcellsantoso** [comment]
@sureshkumarece mind sharing the modified code? thanks!

**Comment by raymondlam** [comment]
I've created a pull request #30 with the ability to set the date range.

**Comment by Marcellsantoso** [comment]
@raymondlam thanks man! :D
