### ISSUE TITLE
Sample App Crash

### ISSUE THREAD

**Issue by bytebeats** [flavienlaurent/datetimepicker#20]
This app can't run on the Samsung s7562 whose Android platform is 4.0.4. Can you check this??

**Comment by flavienlaurent** [comment]
If you have some stacktrace. That d be great

**Comment by bytebeats** [comment]
Yes, it shows NotFoundedException like this:
![qq20131129162100](https://f.cloud.github.com/assets/4122407/1643700/1064ce5e-58d0-11e3-8a28-c4869442be9f.png)

**Comment by flavienlaurent** [comment]
Do you have some custom testing situation?

**Comment by bytebeats** [comment]
Ah? What does that mean? I didn't do that. Whether did I uninstall some
system services? I had rooted my device...

_Peter Pan_

_Android App Development Engineer @ Slanissue Technology Ltd._

_Graduation From International School of Software, *_Wuhan University in
June,2013.*

_Software Engineering Major._

_Mobile:+86 18501223902_

_-------------------------------------------_

_Inner peace matters._

2013/12/2 Flavien Laurent notifications@github.com

**Comment by flavienlaurent** [comment]
Rooted device, ROM custom? Language?

**Comment by bytebeats** [comment]
[image: 内嵌图片 1]ROM is not custom. And Language is English.

_Peter Pan_

_Android App Development Engineer @ Slanissue Technology Ltd._

_Graduation From International School of Software, *_Wuhan University in
June,2013.*

_Software Engineering Major._

_Mobile:+86 18501223902_

_-------------------------------------------_

_Inner peace matters._

2013/12/2 Flavien Laurent notifications@github.com

**Comment by bytebeats** [comment]
The sample is installed on my device now. But there is an other question. When I imported the master into my Eclipse, the both projects show red toggles. It only can be resolved by setting minSdkVersion and targetSdkVersion of both projects 19. But 19 is higher than the version level of my device. So it a trouble for me. So could you please help me handle this??

**Comment by flavienlaurent** [comment]
What's red toggles details?

**Comment by bytebeats** [comment]
for these three:
![qq20131204094024](https://f.cloud.github.com/assets/4122407/1669898/2c0cd8be-5c85-11e3-8691-354258116d5c.png), it shows Not Resource Found...
![qq20131204095026 1](https://f.cloud.github.com/assets/4122407/1670193/156680ec-5c8f-11e3-9b8e-ad5cc5bc5ce4.png)

**Comment by flavienlaurent** [comment]
Not Resource Found on what? It must be on a specific attribute.
For your second issue, you have more details in Eclipse logs.

**Comment by bytebeats** [comment]
<style name="AppBaseTheme" parent="android:Theme.Holo.Light.DarkActionBar">
        
    </style>
and android:importantForAccessibility="no" 
And thanks for your patience.
