### ISSUE TITLE
No 24 hour mode in demo app

### ISSUE THREAD

**Issue by brejoc** [flavienlaurent/datetimepicker#24]
Seems like the time picker only supports am/pm style, which is a no-go e.g. in Germany.

**Comment by supermarcos** [comment]
Hi Brejoc!
It should work perfectly on 24 hours mode. It pretty much depends on the configuration your device has. If your device is configured as 12 hours it will work as AM/PM way, but if your device is configured as 24 hours mode (in Spain we use this as well) it should be shown as that. It displays two wheels, one inside another. Very convenient and creative.
Bye!

**Comment by brejoc** [comment]
Hi supermarcos,

and thanks for your reply. I tried this in the demo app and there the picker only shows am/pm-mode - even on my Nexus 4 with German language settings and German time zone, aso. I will take a look at this.

Bye
Jochen

**Comment by edisonw** [comment]
@brejoc it should work via the device setting. (see SleepBot in the play store that uses this)

**Comment by brejoc** [comment]
@edisonw in SleepBot its working flawlessly. Thanks. Seems like the [demo app](https://raw.github.com/biboune/datetimepicker/master/datetimepicker-sample.apk) has a glitch: http://img59.imageshack.us/img59/5282/u75y.png

**Comment by flavienlaurent** [comment]
What is the problem ?

**Comment by JavierSegoviaCordoba** [comment]
Hello, I am using this picker but always works in am/pm mode. My phone is on 24 hour mode (the alarm picker and calendar picker for example show the picker with 24 hour mode). Where is the problem?
