### ISSUE TITLE
Add support for different times

### ISSUE THREAD

**Issue by Gabryxx7** [flavienlaurent/datetimepicker#25]
Hi, I'm trying this awesome timepicker, and I wanted to ask if there is the possibility to customize it and give the ability to choose different layouts. For example it would be good to be able to choose minutes and minutes again, for displaying a time like 59'59".

I tried to modify it but I think I'm doing something wrong, it should not be so hard to do but I don't know how to display two times the minutes radial picker... At the moment I was only able to display time like 24'59" with different separator... but as you can see I can only choose times from 1 to 24 for the first part of the time...
Is it possible to add the possiblity to choose between 1 and 60 for both parts of the time? Thanks, Gabriele

**Comment by flavienlaurent** [comment]
I don't understand well what you want to do.
Anyway, the TimePicker must be a time picker not a duration picker if it is what you want to do.
