### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by Shusshu** [flavienlaurent/datetimepicker#27]
I see you prepared it for maven central a month ago but you never got it published.
Did you have any issues?

**Comment by flavienlaurent** [comment]
It's on maven central.

with gradle

compile 'com.github.flavienlaurent.datetimepicker:library:0.0.1@aar'

**Comment by Shusshu** [comment]
Strange, I can't find it:
http://search.maven.org/#search%7Cga%7C1%7Ccom.github.flavienlaurent.datetimepicker

**Comment by flavienlaurent** [comment]
maybe, we have to wait a little bit, but it's here https://oss.sonatype.org/content/repositories/releases/com/github/flavienlaurent/datetimepicker/library/

**Comment by Shusshu** [comment]
Did you do the last steps on sonatype Nexus by selecting release?

**Comment by flavienlaurent** [comment]
Yep, just wait
