### ISSUE TITLE
Link to Recurrence picker

### ISSUE THREAD

**Issue by Shusshu** [flavienlaurent/datetimepicker#28]
I have taken the recurrence picker from google calendar and made a lib out of it

I think it would be good to add a link to it in your readme as people who needs calendar pickers probably also need a recurrence picker
https://github.com/Shusshu/Android-RecurrencePicker

**Comment by edisonw** [comment]
Can you provide a legit license at bottom just for the sake of it? :)

**Comment by intrications** [comment]
@Shusshu I agree with @edisonw 

Especially since most (all?) of the code is already Apache 2 licensed and stated as such in the actual source code, it would make sense to use that.

**Comment by Shusshu** [comment]
The beerware is a valid license ;)
anyway the license apache 2 was already in the pom I now have put it also in the readme

**Comment by chrisonline** [comment]
Ist this also for 2.1+?

2014/1/21 Benoit Billington notifications@github.com

> The beerware is a valid license ;)
> anyway the license apache 2 was already in the pom I now have put it also
> in the readme
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flavienlaurent/datetimepicker/issues/28#issuecomment-32831819
> .

## 

Mit freundlichen Grüssen

## Christian Grasser

_COL-ChrisOnLine_
Prof. Hans Hömberg Strasse 11, A-6300 Wörgl
web: www.chrisonline.at
mail: info@chrisonline.at
msn: info@chrisonline.at
twitter: chrisonline1205 http://www.twitter.com/chrisonline1205
skype: chrisonline1205
icq: 6730748

**Comment by Shusshu** [comment]
Not yet now it's only 4+ but work could be done to support 2.1+ or 2.2+ or 2.3+

**Comment by flavienlaurent** [comment]
done
