### ISSUE TITLE
Not compatible with api 8

### ISSUE THREAD

**Issue by benoffi7** [flavienlaurent/datetimepicker#31]
In DatePickerDialog the line "monthDayAnim.setStartDelay(500L);" says  "Call requires API level 11 (current min is 8): android.animation.ObjectAnimator#setStartDelay"

**Comment by benoffi7** [comment]
In Utils this method  "getPulseAnimator" also gives "Call requires API level 11"

**Comment by flavienlaurent** [comment]
Double check your import statements.
It uses NineOldAndroids https://github.com/flavienlaurent/datetimepicker/blob/master/datetimepicker-library/src/com/fourmob/datetimepicker/date/DatePickerDialog.java?source=c#L19
