### ISSUE TITLE
Select date by single tap on the calendar day button and close the widget 

### ISSUE THREAD

**Issue by MariuszGSL** [flavienlaurent/datetimepicker#35]
Is there a way to change the default behaviour of the date picker:
by allowing users to select a date from the calendar with a single-tap on the calendar day, which would select the date and close the widget, instead of having to tap the Done button below the calendar ?
An alternative would be to allow long press to achieve the above.
This would significantly improve the data entry flow and user-friendliness of your date-picker in some applications.
This is the key request from several users testing the above in my app.

**Comment by flavienlaurent** [comment]
Please check this (ee27402ab8a559c6c3687e4559d537604685f388) out. Tell me if this is what you expected ;)
