### ISSUE TITLE
The Done button of TimePicker doesn't appear in small screens

### ISSUE THREAD

**Issue by Angelmmiguel** [flavienlaurent/datetimepicker#36]
I'm using the library in an app and some of my users are telling me that they can't select the hour.

**Comment by flavienlaurent** [comment]
This is a little bit to short as a bug description. Please provide some screenshot, app name etc

**Comment by Angelmmiguel** [comment]
Sorry Flavien :)

I'm using your library in my project: Arpil Medicines ( https://play.google.com/store/apps/details?id=org.arpil.arpil&hl=es ). When the user click on the button "add hour" in the activity "Add Medicine", your time selector is launched.

An user told me "I can't select the hour in your application in my telephone ( http://www.lg.com/uk/mobile-phones/lg-E400-optimus-l3 )!". This telephone has an small screen, so I start an emulator with that resolution. When your time selector is launched I can't see the button "done", because the screen is too small.

Firstly, I forked your library to adapt the time selector on small devices, but later, I thought that the better solution is to change to the classical time selector when the device has a small screen.

I hope this help. 

Thanks and sorry for my bad english ;).

**Comment by flavienlaurent** [comment]
It's not a small screen, it's a watch :smile:

**Comment by Angelmmiguel** [comment]
That's true jajajaj. Thanks for responses ;).
