### ISSUE TITLE
Request: Dark theme

### ISSUE THREAD

**Issue by spacecowboy** [flavienlaurent/datetimepicker#4]
Would it be possible to get a dark version of this? Or attributes which can be overwritten in a custom theme?

**Comment by anoopch** [comment]
Isn't it easy to change the color values and the theme property from the XML files?

**Comment by MiguelCatalan** [comment]
Yes, but if you want to use it in more than one project, themes are necessary

**Comment by spacecowboy** [comment]
My use case is a single app that supports several themes. It's easy to change the existing XML for a single theme, but to support several, a lot of changes become necessary.

**Comment by flavienlaurent** [comment]
It's a good idea to have themes. Feel free to pull a request ;)
It doesn't look like it's a issue.
