### ISSUE TITLE
Setting Range for Date

### ISSUE THREAD

**Issue by ghost** [flavienlaurent/datetimepicker#42]
Let me know if u r providing any option for setting range for date. 
1.Firstly init or initialization is not working. It starts from current date.
2. Unable to hide previous dates.

Read all these issues are fixed. Why is not features merged.
I t would be great,,if done

**Comment by 3mph4515** [comment]
@r4jjin Any ideas or workarounds?

**Comment by kmlkrk** [comment]
I implemented this great picker yesterday without issues. I used that for date range:
datePickerDialog.setYearRange(1985, 2028);

In my case I only wanted current year and the next 15 years so I did something like:
datePickerDialog.setYearRange(calendar.get(Calendar.YEAR), calendar.get(Calendar.YEAR) + 15);

Beware that when I tried setting date range to 30 years in the future it crashed. 20 years was fine. I settled for 15.

**Comment by 3mph4515** [comment]
@kmlkrk But what if i need to set range for weeks or days, not years?

**Comment by ghost** [comment]
@kmlkrk  updated MAX_YEAR = 2115 in DatePickerDialog library class.
Just modified DatePickerDialog, everything works,like charm.

**Comment by sohayb** [comment]
@3mph4515 :+1:

**Comment by delajose90** [comment]
@3mph4515 Hi, you find a solution for this?, to set range for weeks and days?.

**Comment by 3mph4515** [comment]
@chiiiky14 No, i didn't.
