### ISSUE TITLE
getSupportFragmentManager()

### ISSUE THREAD

**Issue by donpeter06** [flavienlaurent/datetimepicker#44]
Inorder to display the picker, the code
        datePickerDialog.show(getSupportFragmentManager(), DATEPICKER_TAG);
has to be called. As it involves support fragment manager I am suck at this point.App has an activity and a GoogleMap fragment and hence not able to use support fragment or fragment activity. I would like to know how i will be able to execute the picker without the use of supportfragmentmanager.

thank-you

**Comment by MarKco** [comment]
I have the same issue. My app supports Android 4+, I don't need SupportFragmentManager but I must have it in order to use this library :-/

**Comment by MarKco** [comment]
Am I maybe getting it wrong?

**Comment by flavienlaurent** [comment]
Just fork the library and replace getSupportFragmentManager by getFragmentManager
