### ISSUE TITLE
Bug from the future!! 

### ISSUE THREAD

**Issue by anoopch** [flavienlaurent/datetimepicker#5]
![screenshot_2013-06-10-01-30-46](https://f.cloud.github.com/assets/4655921/629314/850a0792-d13f-11e2-8825-b6f8dd42d794.png)

See calender from 2038 January. The year says 1901 and month corresponding to December.  Kindly check the same.

**Comment by flavienlaurent** [comment]
fixed by bounding the min and max year (1902 -> 2037, regarding to https://code.google.com/p/android/issues/detail?id=13050)

https://github.com/biboune/datetimepicker/commit/a2b22cca2239aa826051aa3a78cf651ea06e610b
