### ISSUE TITLE
function setCloseOnSingleTapDay() in datePickerDialog is not recognized

### ISSUE THREAD

**Issue by yiyanghu** [flavienlaurent/datetimepicker#53]
I was trying to recreate and modify the sample project but this line gives me errors:

datePickerDialog.setCloseOnSingleTapDay(isCloseOnSingleTapDay());

Even for the code auto-completion, the function setCloseOnSingleTapDay() was not shown.

Thanks for the help!

**Comment by flavienlaurent** [comment]
You have to use 0.0.2 version

**Comment by yiyanghu** [comment]
Awesome, I will try then!
Do you mind updating the last version to be 0.0.2 on the readme page so other people can know as well? Thanks!
