### ISSUE TITLE
Custom Calendar

### ISSUE THREAD

**Issue by arminbashizade** [flavienlaurent/datetimepicker#55]
is there a way to use a customized calendar (e.g. Persian Calendar which is extended from java.util.Calendar) with the DatePicker?
(I mean customized name of the weekdays, name of the months, number of days in months, and font)

**Comment by arminbashizade** [comment]
figured out number of days in months myself

**Comment by arminbashizade** [comment]
almost done :smile:

**Comment by sgkhode** [comment]
how did you customize month names? Can you please share?

**Comment by arminbashizade** [comment]
month names are used in these places:
DatePickerDialog.java, line 176
SimpleMonthView.java, line 148
