### ISSUE TITLE
Vibrate does not work on HTC One

### ISSUE THREAD

**Issue by mustangxl** [flavienlaurent/datetimepicker#62]
Hi, 
I tried the apk and the also the module and it's not vibrating in HTC One !
I Will work around and implement a vibrate function but I just wanted to let you know.

Nice work though.

**Comment by flavienlaurent** [comment]
HTC One? Does it work on other devices?

**Comment by kmlkrk** [comment]
Vibrate works for me on HTC One M7 but it is very short, almost unnoticeable vibration, which I actually like. Thank you so very much for putting this all together!
