### ISSUE TITLE
com.fourmob.datetimepicker.Utils.getDaysInMonth(int month, int year)

### ISSUE THREAD

**Issue by Presleyzheng** [flavienlaurent/datetimepicker#67]
public static int getDaysInMonth(int month, int year) {
        switch (month) {
            case Calendar.JANUARY:
            case Calendar.MARCH:
            case Calendar.MAY:
            case Calendar.JULY:
            case Calendar.AUGUST:
            case Calendar.OCTOBER:
            case Calendar.DECEMBER:
                return 31;
            case Calendar.APRIL:
            case Calendar.JUNE:
            case Calendar.SEPTEMBER:
            case Calendar.NOVEMBER:
                return 30;
            case Calendar.FEBRUARY:
                 //return (year%4==0&&year%100!=0||year%400==0)?29:28;
                return (year % 4 == 0) ? 29 : 28;
            default:
                throw new IllegalArgumentException("Invalid Month");
        }
    }

**Comment by flavienlaurent** [comment]
??

**Comment by Presleyzheng** [comment]
[this line is error](https://github.com/flavienlaurent/datetimepicker/blob/master/datetimepicker-library/src/com/fourmob/datetimepicker/Utils.java#L35)
it should be 
`
return (year%4==0&&year%100!=0||year%400==0)?29:28;
`
