### ISSUE TITLE
import library in eclipse

### ISSUE THREAD

**Issue by giagi87** [flavienlaurent/datetimepicker#70]
Hi

i'm using eclipse and i would like to use your library.
i import the source jar from here http://central.maven.org/maven2/com/github/flavienlaurent/datetimepicker/library/0.0.2/ 
into libs but when i import com.fourmob.datetimepicker.date.DatePickerDialog into my class eclipse not find that.
how can i import the library?

PS.android.support.v4 and nineoldandroid 2.4 are already imported

**Comment by flavienlaurent** [comment]
Don't use Eclipse, use Android Studio
