### ISSUE TITLE
Not button visible on small devices

### ISSUE THREAD

**Issue by benoffi7** [flavienlaurent/datetimepicker#71]
![device-2014-10-03-121026](https://cloud.githubusercontent.com/assets/971363/4507795/93f39cfa-4b0f-11e4-8238-398cf3ce21f2.png)

Thanks for adding scroll or the button on the top

**Comment by artem-sh** [comment]
I confirm, demo app on LG Optimus (320×480 px, 3 inch) has an issue: the OK button is not visible. This is related only to DatePicker, TimePicker fits into the screen.

**Comment by artem-sh** [comment]
@flavienlaurent , I created and tested the example you provide with DateTimePicker on LG Optimus - and the OK button was right where it should be! I suppose, the demo apk is juast a bit outdated. It really looks like there is no issue in the current latest (0.0.2) release.

**Comment by flavienlaurent** [comment]
Yep the demo apk must be outdated. Thanks!
