### ISSUE TITLE
How to permanently turn off vibration

### ISSUE THREAD

**Issue by MariuszGSL** [flavienlaurent/datetimepicker#9]
Your widget currently enforces vibration on touch.
I want to permanently turn off the vibration.

I have tried to remove the vibration permission in your sample application by commenting out the following in the AndroidManifest.xml:
uses-permission android:name="android.permission.VIBRATE" 

However, this causes your sample demo to freeze when the Done button is pressed.
Please advise what needs to be done to disable this annoying "feature" in your library.

**Comment by gabrielittner** [comment]
Just remove the code that is in the tryVibrate method in the DatePickerDialog. Isn't too hard to find, there are only 8 classes in this library.

**Comment by MariuszGSL** [comment]
Thanks. I have actually done exactly that, before I sent my original query.
But I thought there might be another more "elegant" way to disable Vibrate.
No doubt, you have done the same in your Timetable app ?
By the way: how did you mange to get the colours for the selected month+date to always show in blue in your application DUE-DATE selector ?

**Comment by gabrielittner** [comment]
Yes I did it this way.
The color thing worked out of box for me.

**Comment by flavienlaurent** [comment]
You can turn off vibration using

``` java
setVibrate(vibrate)
newInstance(listener,year,month,day,vibrate)
```

3b7481c5357e5134875c9daf7f3807bf9488e553

**Comment by MariuszGSL** [comment]
Thank you. The new switch works very well.
